name = "krakudoteste"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = [
  "/tools/counter/*",
  "/*/tools/counter/*"
]

[dev]
port = 3000

[observability.traces]
enabled = true
